version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: test_effectivemobile_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5467:5432"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test_effectivemobile_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres